import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    //position: 'relative',
    backgroundColor: '#fff',
    position: 'relative',
  },
  text: {
    fontSize: 15,
    padding: 20,
    marginLeft: 8,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  button: {
    backgroundColor: '#168C50',
    height: 61,
    width: 154,
    borderRadius: 154 / 2,
    borderBottomLeftRadius: 154 / 4,
    borderTopRightRadius: 154 / 4,
  },
  buttonView: {
    position: 'absolute',
    padding: 10,
    top: 464,
    left: 110,
    right: 111,
    bottom: 287,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  topLogoView: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    top: 106,
    left: 86,
    right: 59,
    bottom: 616,
  },
  topLogo: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    padding: '50%',
  },
  topLeafeView: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    top: 241,
    left: 8,
    right: 19,
    bottom: 445,
    //height: '50%',
  },
  topLeafe: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    padding: '60%',
  },
  bottomLeafeView: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    top: 284,
    left: 11.36,
    right: 11.87,
    bottom: 417.5,
    //height: '50%',
  },
  bottomLeafe: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    padding: '60%',
  },
  bottomLogoView: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    top: 590,
    left: 0,
    right: 0,
    bottom: 0,
    //height: '50%',
  },
  bottomLogo: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    padding: '50%',
  },
});
export default styles;
